### ISSUE TITLE
[PPconverter] Define relation between record and TUM

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#17] opened 2016-08-04 08:05 UTC
When a file from Philharmonie is parsed, the related TUM is searched, parsed and converted also. (this is not happening if the file is already a TUM). As result, the output consists in 2 Expressions, 2 Works, etc.

An example (it is a summary):

```
<http://data.doremus.org/Self_Contained_Expression/F22/c1f26cc1-74ce-485e-b61b-f89d9d23e1d0>
  a            frbroo:F22_Self-Contained_Expression ;
  mus:U10_has_order_number       "no 5" ;
  cidoc-crm:P102_has_title       "Concerto L'Empereur" , "Concerto pour piano et orchestre no 5" ;

<http://data.doremus.org/Expression_Creation/F28/7fefe1ed-66e0-40a3-952f-bcf9356827c5>
  a       frbroo:F28_Expression_Creation ;
  frbroo:R17_created  <http://data.doremus.org/Self_Contained_Expression/F22/c1f26cc1-74ce-485e-b61b-f89d9d23e1d0> ;


<http://data.doremus.org/Self_Contained_Expression/F22/33c76b60-6587-4926-b2b0-188552724f74>
  a            frbroo:F22_Self-Contained_Expression ;
  mus:U11_has_key    <http://data.doremus.org/vocabulary/key/10> ;
  cidoc-crm:P102_has_title       "Concerto pour piano et orchestre no 5 \"L'empereur\"" ;

<http://data.doremus.org/Expression_Creation/F28/8aefefb3-4eac-4e13-8dba-4998c5d8688f>
  a         frbroo:F28_Expression_Creation ;
  frbroo:R17_created    <http://data.doremus.org/Self_Contained_Expression/F22/33c76b60-6587-4926-b2b0-188552724f74>;
  cidoc-crm:P9_consists_of    [ a           cidoc-crm:E7_activity ;
        mus:U31_had_function_of_type  "compositeur"@fr ;
        cidoc-crm:P14_carried_out_by  [ a       cidoc-crm:E21_Person ;
                cidoc-crm:P131_is_identified_by
                  "Beethoven, Ludwig van(1770-1827)"
                    ]
            ] .
```

The two instances are talking about the same thing but they have no connection between them.

Should we add a link (like put them under the same Complex Work)?
Or they describes exactly the same thing and they should be converted in a unique instance (with maybe different Identifier Assignments and Controlled Access Point)?

@marie-ototoi

**Comment by rtroncy** [comment] 2016-08-04 09:05
I don't understand why you have created two different F22 in the first place? In which case is this happening? Perhaps you can show this with the original data?

**Comment by pasqLisena** [comment] 2016-08-04 09:25
I try to explain it.

We have 2 types of records from Philarmonie (actually more, but we are parsing only these):
- with code `AIC:14`, that is a TUM (_titres uniformes musicaux_);
- with code `UNI:100`, that is a _notice d'oeuvre_

For the latter, we load the related TUM (the code/filename is specified in a field of the file). So we convert the `UNI:100` and the TUM.

The problem is that the two conversion are made separately, but for sure there is a relation between them.

**Comment by rtroncy** [comment] 2016-08-04 10:43
Examples always help to understand problems :-) So, this is a good question which has been discussed with @marie-ototoi and reported in our  joint [IFLA satellite paper](https://drive.google.com/file/d/0B07-9WSsWiOuaEJzXzZHMEJVaEk/view), read the paragraph under the Table 1. The text describes what are the rules when meeting either a TUM or a work entry.

It is indeed important that the converter first discovers what a particular record is describing, so that it can instantiates the appropriate DOREMUS classes.

**Comment by pasqLisena** [comment] 2016-08-04 13:49
So I read the IFLA paper and [this summary by PP](https://drive.google.com/open?id=0B_oqgmkXcLOvNHdXUUxPUHpCNlE) that is on Drive.
In particular:
> [TUMs] n'ont qu'un rôle d 'accès. Ils ne comportent que les renseignements indispensables à l’identification simple et rapide de l’œuvre musicale. C’est la notice d’œuvre qui contient le plus d’informations. 

So, the TUM and the UNI100 describe **the same Work/Expression**.

There are some EXCEPTIONS of **UNI100 linked to different TUMs**:

1. Nocturnes de Chopin: il existe un TUM par nocturne mais une notice d'oeuvre par Opus.
2. Ensemble homogène (24 caprices de Paganini, Clavier bien tempéré, cycle de Lieder) : Pour les ensembles dont on rencontre des extraits, nous faisons un TUM générique, plus un TUM spécifique par extrait présent dans la base de la médiathèque. Les liens entre TUM et notices bibliographiques sont donc faits de la manière suivante : un lien avec l’ATUM générique uniquement pour un document présentant l’œuvre complète, et des liens avec l’ATUM générique et les ATUM spécifiques dans le cas d'extraits.
3. Versions successives d'une oeuvre par le même compositeur : une seule notice d'oeuvre a été réalisée (avec, éventuellement, des liens vers plusieurs TUM)

For points 1 and 2, we can clearly use `P148 has component`. But what about point 3? How to link it? How to distingue it from other cases?

Moreover there are **UNI100 linked to other UNI100**. They are for example "transcriptions" (other derivations also?). It is not clear if in these cases a TUM is present (but this is simple, we simply check if there is).

**Comment by rtroncy** [comment] 2016-08-04 16:51
We have <http://data.doremus.org/vocabulary/derivation/14> (label is "Transcription"@fr") in the derivation scheme, so yes, it seems that your UNI100 linked to other UNI100 case is a derivation between F22.

For your point 3, you're asking if multiple versions of a work from the same composer should be considered as a single work or as multiple ones? Can you provide an example of such a case? / cc @marie-ototoi and @pierrechoffe

**Comment by pierrechoffe** [comment] 2016-08-04 19:33
A typical case would be most Bruckner symphonies, e.g. symphonie nr.8. They have the same catalogue number but the dates are different. So they are Expressions of the same Work (in the FRBR sense), i.e. their F14_Individual_Work are all R10_members of the same F15_Complex_Work.
So how do we recognize them? Simply by the fact that they have the same composer, same name _and_ same catalogue number, but different composition date (F28->E52) and different identifiers in the records.

Either we add a specific derivation name for this in our derivation controlled vocabulary, and create an R2_is_derivative link and type our new Expression with "whateverNameWeWillHaveChosen", or we consider that the F28_Expression_Creation of version 2 p16_used_specific_object the F22_Self_Contained_Expression of version 1. I would prefer the latter because it is more "semantically correct". A new version is not a derivation, it is a revised version taking the preceding version as an object/material upon which to build version 2. Furthermore, this allows us to avoid typing the new version (if we consider that the way we will deal with derivations is to type the derived version, which is not yet decided).

Just for fun : in some _very_ tricky cases, you have versions which are produced by musicologists (Haas version of Bruckner nr.8) and they sometimes happen to be the preferred version of conductors (Haas version). In this case the Haas version is clearly a derivation, but since it takes pieces of each version, we could consider that it is a derivation of all the previous versions. Or even better : a derivation of the F15_Complex_work of the "real" Bruckner versions. Then there would be an additional F15_Complex_Work that would have this F15 as member, plus the Haas version. But this may be a little bit too complex... :)))
Tout ça sans parler des éditions critiques et autres versions plus ou moins oubliées. Si ça vous intéresse, l(article Wikipedia résume bien tout ça: https://fr.wikipedia.org/wiki/Symphonie_n%C2%BA_8_de_Bruckner

**Comment by rtroncy** [comment] 2016-08-05 08:29
Thanks for the example @pierrechoffe. Coming back to the problem at hand, I'm trying to interpret what you're saying and transform into concrete actions (as what an algorithm does). This is what I'm coming with, so please, check and confirm or bring the appropriate corrections:
* The single *notice d'oeuvre* should lead to the instantiation of a F15_Complex_Work
* Each TUM should lead to the instantiation of a F14_Individual_Work

Next, you're suggesting that the information about the composer or even the catalogue number be attached to the F15 (via a F22) while information about the composition date would be attached to the F14 (via another F22). We have the r_10 property that relates the various F14 to the F15 and we will need to add some specific axioms if we wish that this mereology relationship actually means inheriting some property-values from the encompassing class.

You're also looking at making explicit what is the relationship between the various F22. Options are:
* Using our derivation controlled vocabulary. You probably don't want to say "type" the F22 (which means adding a class) but rather attach it to the new ```skos:Concept``` to create in the derivation vocabulary. Later on, you're keeping this ambiguity that derivations will be types. I'm confused.
* Using the existing p16 property ... which is your preferred solution but seems also to convey a more general meaning that this particular use ... which triggers the question: should we create a specific subProperty of p16 for this narrower meaning or are we fine to use the general ```used_specific_object``` property?

**Comment by pierrechoffe** [comment] 2016-08-05 17:01
>- The single notice d'oeuvre should lead to the instantiation of a F15_Complex_Work
- Each TUM should lead to the instantiation of a F14_Individual_Work

Yes (although each institution has its own way of dealing with this, so we should check with all 3 to be sure)

>Next, you're suggesting that the information about the composer or even the catalogue number be attached to the F15 (via a F22) while information about the composition date would be attached to the F14 (via another F22). 

I am not suggesting anything of this kind : information about the composer should always be attached to an event (since he is the actor) as well as information about the composition date, and all the usual informations we find on events : places, manifestation singleton, etc.
If there are two versions, this means that there are two Expression Creation events, on which the usual informations are attached : composer, date, place, etc.

Then, if we have 2 versions, we have two F22 and two F14. Each F14_Individual_Work is a member of the F15_Complex_Work (F15 r10_has_member F14) and each F22 realises the F15 (F15 r3_is_realised_in F22). If an institution has decided that one of these F22 is the representative Expression, then instead of r3, the link between *this* F22 and F15 is r40 instead of r3 (F15 r40_has_representative_expression F22).

>You probably don't want to say "type" the F22 (which means adding a class) but rather attach it to the new skos:Concept to create in the derivation vocabulary. Later on, you're keeping this ambiguity that derivations will be types. I'm confused.

Maybe I was confused. When we first talked bout the problem of typed properties, and more specifically of the type of derivation, I made some suggestions and you suggested that we could just keep the r2_is_derivative_of property and instead of typing the property, to type the derived Work, which I found very smart : for example, Franz Liszt's transcription of Berlioz "Harold in Italy" could be typed as a transcription, it is actually the type of this work.
But maybe I misunderstood what you meant?

>should we create a specific subProperty of p16 for this narrower meaning or are we fine to use the general used_specific_object property?

Yes absolutely, I didn't mention it because I just gave the general frame. But yes, we must create a specific property, otherwise it makes no sense.

**Comment by rtroncy** [comment] 2016-08-07 21:51
Thanks for the clarification. Indeed, contextual information (when, where, etc.) are attached to the event.

> Maybe I was confused. When we first talked bout the problem of typed properties, and more specifically of the type of derivation, I made some suggestions and you suggested that we could just keep the r2_is_derivative_of property and instead of typing the property, to type the derived Work, which I found very smart : for example, Franz Liszt's transcription of Berlioz "Harold in Italy" could be typed as a transcription, it is actually the type of this work.
But maybe I misunderstood what you meant?

Where did you think that the subclass will happen? If at the Work level, then how you would imagine the relationship between the corresponding Expression? This would anyway defeats the purpose of creating a controlled vocabulary for derivation, which we have done. The problem is that r2 is a ternary property since this property indicates that a work W1 is a derivation of a work W2 according to a type of derivation d defined in a SKOS vocabulary. There are various ways for solving this problem, but as always, since I like examples, can you point to the record_1 that describes "Harold in Italy" by Berlioz and the record_2 that describes Franz Liszt's transcription. I would like to see how the former Work is referenced from the later and how the derivation information is encoded.

**Comment by pasqLisena** [comment] 2016-08-11 15:06
I fixed the behavior.

Exceptions are not yet managed.

**Comment by marie-ototoi** [comment] 2016-08-28 12:33
Sorry about replying so late. 

On our side : our preferred title + infos about the work are in the work entry (AIC14), and then it links to the TUM - which was usually taken from BnF so it can help for alignment and might contain info which are not in AIC14. In the mapping rules we have detailed for each line where the info should be taken (if AIC or TUM should be preferred or if they should be combined). 

In works with several parts, it can be that we have one AIC and TUM for the main part and then only TUMS for the parts :
Ex: Dix petits Motets 
Main : UNI100:0906215 / AIC14:0906204
Parts TUM:0906205 / TUM:0906206 / TUM:0906207 / TUM:0906208 / TUM:0906209 / TUM:0906210 / TUM:0906211 / TUM:0906212 / TUM:0906213 / TUM:0906214

**Comment by pierrechoffe** [comment] 2016-09-07 16:33
@rtroncy coming back to you regarding derivations.

attached are two BnF records of "Harold en Italy", the original by Berlioz and the transcription by Liszt.
Also attached the updated version of a document I sent you in May regarding alternative ways of modeling the derivation.

In short : 
* The records link to each other
* The TUM of Liszt mentions the derivation type as its first argument : "Transcriptions", then the composer "Berlioz, Hector", then the title and catalogue number of the original work "Harold en Italie H68", then the mediums of performance of the transcription "Alto, Piano", then the Liszt catalogue number "LW D5"
* interestingly, there are 3 different catalogues (see alternative catalogues in 444 $k)

in the Typed Property document, p.1 is the FRBRoo model, then p.2-5 are 4 alternatives.
* alt1 uses an event (kind of heavy, but more informative)
* alt2 is a simple reification using rdf props
* alt3 types the derived Work
* alt4 types the derived Expression

Do you think one of them might do?

[liste de notices complètes 07_09_2016 17_59.pdf](https://github.com/DOREMUS-ANR/marc2rdf/files/459655/liste.de.notices.completes.07_09_2016.17_59.pdf)
[liste de notices complètes 07_09_2016 17_57.pdf](https://github.com/DOREMUS-ANR/marc2rdf/files/459656/liste.de.notices.completes.07_09_2016.17_57.pdf)
[CLP Derivation 2.pdf](https://github.com/DOREMUS-ANR/marc2rdf/files/459658/CLP.Derivation.2.pdf)

**Comment by pasqLisena** [comment] 2016-09-08 08:00
I think that alt3/4 are the clearer ones. I prefer alt3 because wee keep the R2 properties of FRBRoo.

BTW we are off topic in this issue 😄

**Comment by rtroncy** [comment] 2016-09-19 11:54
We are definitively off topic for this issue :smile: !

@pierrechoffe, reflecting on your 4 options:
 * alt2 is invalid ... ```rdfs:domain``` and ```rdfs:range``` are properties that have for domain an ```rdf:Property``` ... not a class!
 * alt3 is simple but what's happen if a F14 has multiple derivations? Can this happen? Furthermore, you don't specify who is saying that a F14 is a derivative of another F14 while I thought this was important to state per your alt1
 * alt4 is also simple but has the same limitations than alt3 in terms of metadata to add about the origin of the derivation. Whether the property should be established between Work or Expression is something to be resolved in an upcoming modeling meeting. Can this be on the agenda? / cc @ccecconi 
 * alt1 is more complex but this complexity is necessary if it is important to assert the origin of the derivation statement. We may argue on the direction of the properties though

**Comment by pasqLisena** [comment] 2016-09-21 13:26
> alt3 is simple but what's happen if a F14 has multiple derivations? Can this happen? 

You are right! A work can be a "Réminiscence"@fr of multiple other ones. For the "Pot-pourri"@fr it happens every time!

> alt1

Now I have a doubt also on this alternative: what if a Work X is an arrangement of Y realizing by adding some Reminiscence to Z?

> We may argue on the direction of the properties though

I think that the "derivation type" should be a property with Work (or Expression) as domain (so _Uyy has derivation type_

> Whether the property should be established between Work or Expression ...

I think it should be at the Work level. Normally we speak about "derivative work" and indeed is an influence of an idea from another one. But if we think to Expressions as "versions" of the same work, then you actually realize, for example, a transcription of a specific version/expression.
We will discuss it better tomorrow, also considering the data we have.

**Comment by pierrechoffe** [comment] 2016-09-21 13:55
@rtroncy @pasqLisena Yes we will discuss these tomorrow with the group !

Meanwhile:
>A work can be a "Réminiscence"@fr of multiple other ones

An F14 may have multiple derivations, but maybe not multiple *derivation types*. We talked about it with Frédéric and Françoise the other day, and although you may sometimes hesitate between 2 types (e.g. transcription and reduction), you will definitely choose one. What may happen is that another institution may choose the other one, but this is another subject.

>Now I have a doubt also on this alternative: what if a Work X is an arrangement of Y realizing by adding some Reminiscence to Z?

see above

> We may argue on the direction of the properties though (alt1)

@rtroncy What property are you talking about? 

>Whether the property should be established between Work or Expression ...

In the FRBRoo model, derivations occur between Works (domain & range of R2 is F1_Work), and in our implementation it should definitely be between 2 F14 (and arguably also at the F15 level).
Now, I agree with Pasquale that we could model them at the Expression level (through a DOREMUS property using the same superproperty as R2 =P130_shows_features_of), which would be consistent with our choice of describing things at the Expression level, not at the Work level.

**Comment by rtroncy** [comment] 2016-09-21 14:21
>> We may argue on the direction of the properties though (alt1)

> @rtroncy What property are you talking about? 

The one you provisionally named ```Uyy_assigned_to```

**Comment by pierrechoffe** [comment] 2016-09-21 14:25
Oh, why ? We have an assignment event ("Derivation Type Assignment") which as usual assigns something (the Derivation Type) to something (the F14 Individual Work) and has an actor (the library). What pb do you see ?

**Comment by pasqLisena** [comment] 2016-09-21 14:30
> An F14 may have multiple derivations, but maybe not multiple derivation types.

Good! Ok, so alt1 could be a valid solution!

> We have an assignment event ("Derivation Type Assignment") which as usual assigns something (the Derivation Type) to something (the F14 Individual Work) and has an actor (the library).

I actually was thinking to the derivation type like an "attribute" (like key, genre, casting, etc.). That's why I see it in the reverse direction.

**Comment by rtroncy** [comment] 2016-09-21 14:34
@pierrechoffe As usual, try to get the consumer point of view ... you start from a Work and you look for derivations ... your entry point will rarely be a derivation type assignment event.

**Comment by pierrechoffe** [comment] 2016-09-21 14:41
OK we will have to talk about this in concrete details (hands-on) :smile:

So if we keep the idea of a Derivation Type Assignment, this means that a property Uyy_was_assigned_derivation_type_by (or shorter!) between F14 and Myy_Derivation_Type_Assignment (in this direction) would be more appropriate, is this what you mean?

**Comment by rtroncy** [comment] 2016-09-21 15:09
Yes, this is what I mean ... iff we consider that alt1 is the way to go. But we need to come back to the data with real examples to see how derivations will be detected from the MARC data and mapped to the model.

**Comment by pierrechoffe** [comment] 2016-09-27 09:51
@rtroncy If we go this way (with a "Uyy_was_assigned_derivation_type_by" property), how will you deal with the other E13 Assignments (Identifier Assignment, Representative Expression Assignment, Award Assignment, etc) ? Should we also create specific properties ? including Doremus specific properties for CRM or FRBRoo used in Doremus representations ? Or isn't it better to have a unique solution (like : "for all assignments we use the inverse prop = was assigned by, instead of assigned") ?

**Comment by rtroncy** [comment] 2016-09-27 13:22
@pierrechoffe There is no absolute answer. Again, you have to put yourself as a consumer of the data (one can always traverse the graph as he needs, but we privilege the direction which presumably will be the most used one). In order to progress on this issue, I'm re-iterating my [previous request](https://github.com/DOREMUS-ANR/marc2rdf/issues/17#issuecomment-248642085): let's come back to the **real data**! Can you provide real marc files that contain the entire complexity of what you're describing: derivative work, representative expression, award, etc.

I observer that this specific issue is about the PP converter and you will probably refer to examples from BnF?

**Comment by pierrechoffe** [comment] 2016-09-27 13:26
>I observe that this specific issue is about the PP converter

Yes we are definitely off-topic, should we open a new issue?

**Comment by rtroncy** [comment] 2016-09-27 13:28
> Yes we are definitely off-topic, should we open a new issue?

Yes.

**Closed** 2017-05-04 14:21 UTC
Labels: question
